### ISSUE TITLE
Adobe tools ?

### ISSUE THREAD

**Issue by melMass** [yglukhov/rod#324]
Hi Yuriy,

I found your repo looking for a nim way to write scripts for Premiere and After Effects, you seem to have mapped the AE API, I can contribute with the premiere one once I'm done, can you explain how you use the Adobe Tools to build and run the nim scripts while developing? I'm not sure to understand and I'm pretty new still to the tooling of nim

**Comment by yglukhov** [comment]
Not sure about Premiere, but check out after_effects_export dir. In this dir run nake to build and install rod_export.nim to after effects ScriptUI extensions.

**Comment by melMass** [comment]
Thanks, yes the nake file is what I was looking for thanks, I'm using only nimble tasks for now but I'll just adapt it. 

How did you go to translate AE API?

**Comment by yglukhov** [comment]
> How did you go to translate AE API?

Manually, nothing fancy.

**Comment by melMass** [comment]
Sorry I meant from what ? The object browser in extendscript ? The API documentation? Sorry to ask but if find it hard to find info about the proper layout of those API, that's mainly why I want to translate it to Nim as you did, to work faster with them.

**Comment by yglukhov** [comment]
I believe I used this one: https://blogs.adobe.com/creativecloud/files/2012/06/After-Effects-CS6-Scripting-Guide.pdf
I think I just googled for after effects javascript reference.

**Comment by melMass** [comment]
You went the hard way, ok thanks, I'll try to automate some of it for the premiere API (which is even less documented)...

Thanks!
