### ISSUE TITLE
Can't build for MacOSX

### ISSUE THREAD

**Issue by nixfreak** [yglukhov/rod#369]
Can't build Rod because of dependency nimx 
`
Compiling nakefile...
Hint: used config file '/Users/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/Users/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
...................................................................................`
/Users/.nimble/pkgs/async_http_request-0.1.2/async_http_request.nim(125, 34) template/generic instantiation of `request` from here
/Users/.choosenim/toolchains/nim-#devel/lib/pure/httpclient.nim(1058, 14) Warning: Deprecated since v1.5; use HttpMethod enum instead; string parameter httpMethod is deprecated [User]
...................................
**/Users/.nimble/pkgs/nimx-0.1/nimx/layout_vars.nim(19, 32) Error: type mismatch: got <Variable>**
but expected one of: 
proc newExpression(constant: float = 0): Expression
  first type mismatch at position: 1
  required type for constant: float
  but expression 'left(phs)' is of type: Variable
proc newExpression(term: Term; constant: float = 0): Expression
  first type mismatch at position: 1
  required type for term: Term
  but expression 'left(phs)' is of type: Variable
proc newExpression(terms: seq[Term]; constant: float = 0): Expression
  first type mismatch at position: 1
  required type for terms: seq[Term]
  but expression 'left(phs)' is of type: Variable

expression: newExpression(left(phs))

**Comment by yglukhov** [comment]
Most likely kiwi dependency is outdated.
```
rm -rf ~/.nimble/pkgs/kiwi*
nimble install -y kiwi
```

**Comment by nixfreak** [comment]
Yep that worked , thanks
